### ISSUE TITLE
Investigate the issues reported to Binnie-Patcher

### ISSUE THREAD

**Issue by mezz** [ForestryMC/Binnie#4]
https://github.com/Chocohead/Binnie-Patcher/issues

We should make sure major the issues reported there are resolved in this version.
- [x] GUIs do not always update their displayed items  https://github.com/Chocohead/Binnie-Patcher/issues/3
- [x] Alveary Mutator Not Guaranteeing Pure Mutation https://github.com/Chocohead/Binnie-Patcher/issues/10
- [x] wax capsules and cans being removed from buildcraft https://github.com/Chocohead/Binnie-Patcher/issues/21
- [x] OreDict wooden gears, please?  https://github.com/Chocohead/Binnie-Patcher/issues/22
- [x] Buckets get eaten  https://github.com/Chocohead/Binnie-Patcher/issues/24
- [x] Saplings are the wrong colors https://github.com/Chocohead/Binnie-Patcher/issues/25
- [x] Disabling Lepidopterology in Forestry causes crash https://github.com/Chocohead/Binnie-Patcher/issues/29

**Comment by Chocohead** [comment]
- The GUI weirdness was to do with the way Binnie implemented them using his own system
- The Alveary Mutator I never fully worked out, it may have cancelled itself out not implementing something properly, but the mutation chance boost was always calculated correctly at the very least
- The wax and cans were strange, I always thought it was compat changing somewhere else triggering it rather than an explicit bug in anything Binnie did
- The gears was a suggestion rather than a bug, it was Gregtech that always used to add them rather than Binnie for older packs (as Greg liked doing that for mods)
- Buckets vanishing was down to Binnie not marking the containers for being reusable from what I remember, or something along those lines
- The missing sapling colour was me forgetting to apply the overlay to the icons when I moved bits around
- The Lepidopterology crash was from Binnie just presuming the items would be there for recipes, potentially from them changing module (or he could have just overlooked it)
